name: Data Pipeline Test

on:
  push:
    paths:
      - 'data/**'
      - 'project/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.13"

    - name: Test with pytest
      run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh
